version: "3"
services:
  mysql:
    image: mysql:8.3.0
    ports:
      - 3380:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: khafan_app
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      MYSQL_DATABASE_HOST: mysql
  nginx:
    image: nginx:1.25-alpine3.18
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
