version: "3"
services:
  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: khafan_app
  app:
    image: khafan_app:v1
    environment:
      MYSQL_DATABASE_HOST: mysql
  nginx:
    image: nginx:1.25.3-alpine3.18
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
